[package]
name = "sfm"
version = "0.2.0"
authors = ["Dan Meehan <dan.meehan17@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion="*"
